/* Generated by Together */

#ifndef TRIANGLE3D_H
#define TRIANGLE3D_H

#include "../v3.hpp"
#include "../m33.hpp"


//template <typename T, bool IS_REFERENCE=false>
class triangle3d
{
public:    

	bool_t                          point_inside(vec_const_reference p);
	

};
#endif //TRIANGLE3D_H
