
add_definitions(
    -DCPAF_PLATFORM_TYPE_ID=${CPAF_PLATFORM_TYPE_ID}
    -DCPAF_SYSTEM_ID=${CPAF_SYSTEM_ID}
    -DCPAF_AUDIO_SYSTEM_ID=${CPAF_AUDIO_SYSTEM_ID}
    -DCPAF_GRAPHICS_SYSTEM_ID=${CPAF_GRAPHICS_SYSTEM_ID}
    -DCPAF_GUI_SYSTEM_ID=${CPAF_GUI_SYSTEM_ID}
    -DCPAF_FILE_SYSTEM_ID=${CPAF_FILE_SYSTEM_ID}
)

message ("CPAF_SYSTEM_NAME          : '${CPAF_SYSTEM_NAME}'")
message ("CPAF_AUDIO_SYSTEM_NAME    : '${CPAF_AUDIO_SYSTEM_NAME}'")
message ("CPAF_GRAPHICS_SYSTEM_NAME : '${CPAF_GRAPHICS_SYSTEM_NAME}'")
message ("CPAF_GUI_SYSTEM_NAME      : '${CPAF_GUI_SYSTEM_NAME}'")
message ("CPAF_FILE_SYSTEM_NAME     : '${CPAF_FILE_SYSTEM_NAME}'")
